platform :ios, '8.0'
use_frameworks!

target 'Giftsay' do
  pod 'AFNetworking', '~> 3.0.0-beta.2'
  pod 'SDWebImage', '~> 3.7.3'
  pod 'MJRefresh', '~> 3.0.6'
  pod 'TencentOpenApiSDK', '~> 2.9.3'
end
